apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: adminer-firewall
  namespace: default
spec:
  podSelector:
    matchLabels:
      aplikacja: panel-adminera
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 192.168.55.0/24
    ports:
    - protocol: TCP
      port: 80
