apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi     # Rezerwujemy 2 GB na konfigurację i Twoje pliki w chmurze
