apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
spec:
  replicas: 1            # Zmniejszamy do 1 na czas pierwszej instalacji, potem podbijesz do 2
  selector:
    matchLabels:
      aplikacja: chmura-nextcloud
  template:
    metadata:
      labels:
        aplikacja: chmura-nextcloud
    spec:
      containers:
      - name: nextcloud-kontener
        image: nextcloud:28
        ports:
        - containerPort: 80
        env:
        - name: NEXTCLOUD_DB_TYPE
          value: pgsql           # Informujemy Nextclouda, że używamy PostgreSQL
        - name: NEXTCLOUD_DB_HOST
          value: postgres-service
        - name: NEXTCLOUD_DB_NAME
          value: sklep_db
        - name: NEXTCLOUD_DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-sejf
              key: login-bazy
        - name: NEXTCLOUD_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-sejf
              key: haslo-bazy
        volumeMounts:
        - name: nextcloud-dane
          mountPath: /var/www/html
      volumes:
      - name: nextcloud-dane
        persistentVolumeClaim:
          claimName: nextcloud-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  type: ClusterIP         # Zmieniono z LoadBalancer na ClusterIP pod Ingressa
  selector:
    aplikacja: chmura-nextcloud
  ports:
  - port: 80
    targetPort: 80
